#include <array>
#include <cctype>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <memory>
#include <optional>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_set>
#include <vector>

#include "../middle_reservoir/middle_reservoir_monitor.hpp"
#include "all_props/axial_profile_x_export.hpp"
#include "all_props/channel_count_xz.hpp"
#include "all_props/coord_x.hpp"
#include "all_props/density_x.hpp"
#include "all_props/density_z_in_x_channel.hpp"
#include "all_props/dipole_x.hpp"
#include "all_props/dipole_z_in_x_channel.hpp"
#include "all_props/gating_flux.hpp"
#include "all_props/jump_msd.hpp"
#include "all_props/water_atom_density_x.hpp"
#include "simio/simio.hpp"
#include "simio/runtime/cache.hpp"
#include "simio/runtime/run_config.hpp"
#include "simio/analysis/intrinsics/x_grid_cache.hpp"
#include "xtc.h"

namespace {

// SIMIO_CACHE_WIRED: minimal cache integration (foundation)
static bool simio_env_flag(const char* name) {
    const char* v = std::getenv(name);
    if (!v) return false;
    return (v[0] == '1' || v[0] == 'y' || v[0] == 'Y' || v[0] == 't' || v[0] == 'T');
}

static void simio_cache_put_run_meta(simio::runtime::CacheStore& cache) {
    using namespace simio::runtime;
    CacheKey k{"run_meta", CacheScope::Global, 0, -1};
    Blob b;
    // Tiny marker payload; this just validates compute-once key wiring.
    b.bytes = {0x52, 0x4d};  // "RM"
    if (simio_env_flag("SIMIO_CACHE_STRICT")) {
        if (!cache.put_strict(k, std::move(b))) {
            std::cerr << "ERROR: duplicate CacheKey computed for run_meta (strict mode)\n";
            std::exit(3);
        }
    } else {
        cache.put(k, std::move(b));
    }
}

static void simio_cache_maybe_print_stats(const simio::runtime::CacheStore& cache) {
    if (!simio_env_flag("SIMIO_CACHE_STATS")) return;
    const auto& s = cache.stats();
    std::cerr << "[simio-cache] gets=" << s.gets
              << " hits=" << s.hits
              << " puts=" << s.puts
              << " dup_puts=" << s.duplicate_puts
              << "\n";
}

struct CliConfig {
    std::string xtc_path;
    int max_frames = 100;
    int frame_begin = 0;   // 0-based inclusive frame index in the trajectory
    int frame_end = -1;    // 0-based exclusive frame index; -1 means until EOF
    int nthreads = 4;
    double grid_cell_nm = 0.5;
    int nsol = 5896;
    int nna = 110;
    int ncl = 110;
    double xmin = 7.11;
    double xmax = 12.89;
    double zmin = 0.901;
    double zmax = 1.801;
    int nx = 100;
    int nz = 0;  // 0 means: reuse nx
    double r_cw = 0.35;
    double r_aw = 0.38;
    double r_oo = 0.35;
    simio::analysis::GatingSelection gating_selection = simio::analysis::GatingSelection::All;
    std::string out_dir = ".";
    int jump_keep_frames = 50;
    double bound_layer_nm = 0.30;

    // Optional auto-setup source generated by mini_gro_topology.cpp.
    std::string topology_json;
    bool use_channel_bounds_from_topology = false;
    std::string water_names = "SOL,WAT,HOH";
    std::string na_names = "NA,NA+,SOD";
    std::string cl_names = "CL,CL-,CLA";

    struct MolBlock {
        simio::MolType type = simio::MolType::Other;
        int nmol = 0;
        int natoms_per_mol = 0;
    };
    // Optional ordered molecule blocks inferred from topology_json types[] order.
    std::vector<MolBlock> mol_blocks;
    bool has_mol_blocks = false;
};

bool has_suffix(const std::string& s, const std::string& suffix) {
    if (suffix.size() > s.size()) return false;
    return s.compare(s.size() - suffix.size(), suffix.size(), suffix) == 0;
}

std::string trim_copy(const std::string& s) {
    size_t b = 0, e = s.size();
    while (b < e && std::isspace(static_cast<unsigned char>(s[b]))) ++b;
    while (e > b && std::isspace(static_cast<unsigned char>(s[e - 1]))) --e;
    return s.substr(b, e - b);
}

std::string upper_copy(std::string s) {
    for (char& c : s) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    return s;
}

std::unordered_set<std::string> parse_name_set_csv(const std::string& names_csv) {
    std::unordered_set<std::string> out;
    std::string cur;
    auto flush = [&]() {
        const std::string t = upper_copy(trim_copy(cur));
        if (!t.empty()) out.insert(t);
        cur.clear();
    };
    for (char c : names_csv) {
        if (c == ',' || std::isspace(static_cast<unsigned char>(c))) {
            flush();
        } else {
            cur.push_back(c);
        }
    }
    flush();
    return out;
}

std::string read_text_file(const std::string& path) {
    std::ifstream ifs(path);
    if (!ifs) throw std::runtime_error("Failed to open JSON config: " + path);
    std::ostringstream oss;
    oss << ifs.rdbuf();
    return oss.str();
}

std::optional<std::string> json_find_string(const std::string& text, const std::string& key) {
    const std::regex re("\"" + key + "\"\\s*:\\s*\"([^\"]*)\"");
    std::smatch m;
    if (std::regex_search(text, m, re)) return m[1].str();
    return std::nullopt;
}

std::optional<std::string> json_find_number_token(const std::string& text, const std::string& key) {
    const std::regex re("\"" + key + "\"\\s*:\\s*([-+]?(?:\\d+\\.?\\d*|\\.\\d+)(?:[eE][-+]?\\d+)?)");
    std::smatch m;
    if (std::regex_search(text, m, re)) return m[1].str();
    return std::nullopt;
}

std::optional<std::string> json_find_string_any(const std::string& text,
                                                std::initializer_list<const char*> keys) {
    for (const char* k : keys) {
        if (auto v = json_find_string(text, k)) return v;
    }
    return std::nullopt;
}

std::optional<std::string> json_find_number_any(const std::string& text,
                                                std::initializer_list<const char*> keys) {
    for (const char* k : keys) {
        if (auto v = json_find_number_token(text, k)) return v;
    }
    return std::nullopt;
}

std::optional<bool> json_find_bool_any(const std::string& text,
                                       std::initializer_list<const char*> keys) {
    for (const char* k : keys) {
        const std::regex re(std::string("\"") + k + "\"\\s*:\\s*(true|false)",
                            std::regex::icase);
        std::smatch m;
        if (std::regex_search(text, m, re)) {
            const std::string token = upper_copy(m[1].str());
            return token == "TRUE";
        }
    }
    return std::nullopt;
}

std::optional<bool> json_find_bool_or_int_any(const std::string& text,
                                              std::initializer_list<const char*> keys) {
    if (auto b = json_find_bool_any(text, keys)) return b;
    if (auto n = json_find_number_any(text, keys)) {
        try {
            return std::stod(*n) != 0.0;
        } catch (...) {
            return std::nullopt;
        }
    }
    return std::nullopt;
}

int parse_int_text(const std::string& s, const char* name) {
    try {
        return std::stoi(s);
    } catch (const std::exception&) {
        throw std::runtime_error(std::string("Invalid integer for ") + name + ": " + s);
    }
}

double parse_double_text(const std::string& s, const char* name) {
    try {
        return std::stod(s);
    } catch (const std::exception&) {
        throw std::runtime_error(std::string("Invalid number for ") + name + ": " + s);
    }
}

std::array<double, 3> parse_array3_numbers(const std::string& s, const char* name) {
    std::array<double, 3> out{0.0, 0.0, 0.0};
    std::istringstream iss(s);
    std::string tok;
    for (int i = 0; i < 3; ++i) {
        if (!std::getline(iss, tok, ',')) {
            throw std::runtime_error(std::string("Expected 3 values for ") + name + ": " + s);
        }
        out[static_cast<size_t>(i)] = parse_double_text(trim_copy(tok), name);
    }
    return out;
}

struct MiniTopologyData {
    struct TypeEntry {
        std::string name;
        int molecules = 0;
        int atoms_per_molecule = 0;  // 0 when unavailable in JSON
    };
    std::array<double, 3> channel_min{0.0, 0.0, 0.0};
    std::array<double, 3> channel_max{0.0, 0.0, 0.0};
    bool has_channel = false;
    std::vector<TypeEntry> types;
};

MiniTopologyData parse_mini_topology_json(const std::string& path) {
    const std::string text = read_text_file(path);
    MiniTopologyData out;

    {
        const std::regex ch_re("\"channel\"\\s*:\\s*\\{([\\s\\S]*?)\\}",
                               std::regex::icase);
        std::smatch m;
        if (std::regex_search(text, m, ch_re)) {
            const std::string ch = m[1].str();
            const std::regex min_re("\"(?:min|min_nm)\"\\s*:\\s*\\[([^\\]]+)\\]",
                                    std::regex::icase);
            const std::regex max_re("\"(?:max|max_nm)\"\\s*:\\s*\\[([^\\]]+)\\]",
                                    std::regex::icase);
            std::smatch min_m, max_m;
            if (std::regex_search(ch, min_m, min_re) && std::regex_search(ch, max_m, max_re)) {
                out.channel_min = parse_array3_numbers(min_m[1].str(), "channel.min|min_nm");
                out.channel_max = parse_array3_numbers(max_m[1].str(), "channel.max|max_nm");
                out.has_channel = true;
            }
        }
    }

    const std::regex obj_re("\\{[^\\{\\}]*\\}");
    for (std::sregex_iterator it(text.begin(), text.end(), obj_re), end; it != end; ++it) {
        const std::string obj = it->str();
        const auto name_v = json_find_string(obj, "name");
        const auto mols_v = json_find_number_token(obj, "molecules");
        if (!name_v || !mols_v) continue;

        MiniTopologyData::TypeEntry e;
        e.name = upper_copy(trim_copy(*name_v));
        e.molecules = parse_int_text(*mols_v, "types[].molecules");
        if (auto apm_v = json_find_number_token(obj, "atoms_per_molecule")) {
            e.atoms_per_molecule = parse_int_text(*apm_v, "types[].atoms_per_molecule");
        }
        out.types.push_back(e);
    }

    return out;
}

void apply_topology_counts_from_mini_json(CliConfig& c) {
    if (c.topology_json.empty()) return;

    const MiniTopologyData topo = parse_mini_topology_json(c.topology_json);
    const auto water_set = parse_name_set_csv(c.water_names);
    const auto na_set = parse_name_set_csv(c.na_names);
    const auto cl_set = parse_name_set_csv(c.cl_names);

    int nsol = 0;
    int nna = 0;
    int ncl = 0;
    bool has_sol = false;
    bool has_na = false;
    bool has_cl = false;
    std::vector<CliConfig::MolBlock> blocks;
    for (const auto& kv : topo.types) {
        const std::string& name = kv.name;
        const int count = kv.molecules;
        std::optional<simio::MolType> mapped;
        if (water_set.count(name) > 0) {
            nsol += count;
            has_sol = true;
            mapped = simio::MolType::Water;
        }
        if (na_set.count(name) > 0) {
            nna += count;
            has_na = true;
            mapped = simio::MolType::Cation;
        }
        if (cl_set.count(name) > 0) {
            ncl += count;
            has_cl = true;
            mapped = simio::MolType::Anion;
        }
        simio::MolType t = mapped.value_or(simio::MolType::Other);
        int natoms_per_mol = kv.atoms_per_molecule;
        if (t == simio::MolType::Water) {
            if (natoms_per_mol == 0) natoms_per_mol = 3;
            if (natoms_per_mol != 3) {
                throw std::runtime_error("topology_json water molecule '" + name +
                                         "' has atoms_per_molecule=" +
                                         std::to_string(natoms_per_mol) +
                                         ", but this driver requires 3 (OHH)");
            }
        } else if (t == simio::MolType::Cation || t == simio::MolType::Anion) {
            if (natoms_per_mol == 0) natoms_per_mol = 1;
            if (natoms_per_mol != 1) {
                throw std::runtime_error("topology_json ion molecule '" + name +
                                         "' has atoms_per_molecule=" +
                                         std::to_string(natoms_per_mol) +
                                         ", but this driver requires 1");
            }
        } else {
            if (natoms_per_mol <= 0) {
                throw std::runtime_error(
                    "topology_json has unmapped molecule '" + name +
                    "' without atoms_per_molecule; cannot preserve atom offset");
            }
        }

        if (count <= 0) continue;
        if (!blocks.empty() && blocks.back().type == t &&
            blocks.back().natoms_per_mol == natoms_per_mol) {
            blocks.back().nmol += count;
        } else {
            blocks.push_back(CliConfig::MolBlock{t, count, natoms_per_mol});
        }
    }

    if (has_sol) c.nsol = nsol;
    if (has_na) c.nna = nna;
    if (has_cl) c.ncl = ncl;
    if (!blocks.empty()) {
        c.mol_blocks = std::move(blocks);
        c.has_mol_blocks = true;
    }

    if (c.use_channel_bounds_from_topology) {
        if (!topo.has_channel) {
            throw std::runtime_error("topology_json missing channel.min/channel.max arrays: " +
                                     c.topology_json);
        }
        c.xmin = topo.channel_min[0];
        c.xmax = topo.channel_max[0];
        c.zmin = topo.channel_min[2];
        c.zmax = topo.channel_max[2];
    }
}

int parse_int_arg(const char* s, const char* name) { return parse_int_text(std::string(s), name); }

double parse_double_arg(const char* s, const char* name) {
    return parse_double_text(std::string(s), name);
}

void validate_cli_config(const CliConfig& c) {
    if (c.xtc_path.empty()) {
        throw std::runtime_error("Missing trajectory path (xtc_path).");
    }
    if (c.frame_begin < 0) {
        throw std::runtime_error("Invalid frame_begin: must be >= 0");
    }
    if (c.frame_end != -1 && c.frame_end <= c.frame_begin) {
        throw std::runtime_error("Invalid frame_end: must be -1 or > frame_begin");
    }
    if (c.max_frames == 0 || c.max_frames < -1 || c.nthreads <= 0 || c.grid_cell_nm <= 0.0 || c.nsol < 0 || c.nna < 0 ||
        c.ncl < 0 || c.nx <= 0 || c.nz < 0 || c.r_cw <= 0.0 || c.r_aw <= 0.0 || c.r_oo <= 0.0 ||
        c.jump_keep_frames <= 0 || c.bound_layer_nm < 0.0) {
        throw std::runtime_error("Invalid non-positive numeric argument.");
    }
    if (c.out_dir.empty()) {
        throw std::runtime_error("Invalid out_dir: must be non-empty");
    }
}

void print_usage(const char* prog) {
    std::cerr
        << "Usage: " << prog
        << " <trajectory.xtc> [max_frames=100] [threads=4] [grid_cell_nm=0.5] [nsol=5896] [nna=110] [ncl=110]"
        << " [xmin=7.11] [xmax=12.89] [zmin=0.901] [zmax=1.801] [nx=100]"
        << " [r_cw=0.35] [r_aw=0.38] [r_oo=0.35] [gating_sel=all] [out_dir=.] [jump_keep_frames=50]"
        << " [frame_begin=0] [frame_end=-1]\n"
        << "   or: " << prog << " --config <config.json>\n"
        << "   or: " << prog << " <config.json>\n"
        << "   or: " << prog
        << " <trajectory.xtc> <ion_insertion_report.json> [defaults.json]\n"
        << "Reactor mode infers <trajectory>.gro, system counts/bounds, and "
           "<output_root>/<trajectory_stem>.\n"
        << "JSON extras: topology_json, use_channel_bounds_from_topology, water_names, "
           "na_names, cl_names, bound_layer_nm, frame_begin, frame_end, output_root\n";
}

CliConfig parse_positional_cli(int argc, char** argv) {
    CliConfig c;
    c.xtc_path = argv[1];
    if (argc > 2) c.max_frames = parse_int_arg(argv[2], "max_frames");
    if (argc > 3) c.nthreads = parse_int_arg(argv[3], "threads");
    if (argc > 4) c.grid_cell_nm = parse_double_arg(argv[4], "grid_cell_nm");
    if (argc > 5) c.nsol = parse_int_arg(argv[5], "nsol");
    if (argc > 6) c.nna = parse_int_arg(argv[6], "nna");
    if (argc > 7) c.ncl = parse_int_arg(argv[7], "ncl");
    if (argc > 8) c.xmin = parse_double_arg(argv[8], "xmin");
    if (argc > 9) c.xmax = parse_double_arg(argv[9], "xmax");
    if (argc > 10) c.zmin = parse_double_arg(argv[10], "zmin");
    if (argc > 11) c.zmax = parse_double_arg(argv[11], "zmax");
    if (argc > 12) c.nx = parse_int_arg(argv[12], "nx");
    if (argc > 13) c.r_cw = parse_double_arg(argv[13], "r_cw");
    if (argc > 14) c.r_aw = parse_double_arg(argv[14], "r_aw");
    if (argc > 15) c.r_oo = parse_double_arg(argv[15], "r_oo");
    if (argc > 16) c.gating_selection = simio::analysis::parse_gating_selection(argv[16]);
    if (argc > 17) c.out_dir = argv[17];
    if (argc > 18) c.jump_keep_frames = parse_int_arg(argv[18], "jump_keep_frames");
    if (argc > 19) c.frame_begin = parse_int_arg(argv[19], "frame_begin");
    if (argc > 20) c.frame_end = parse_int_arg(argv[20], "frame_end");

    validate_cli_config(c);
    return c;
}

CliConfig parse_json_cli(const std::string& json_path) {
    const std::string text = read_text_file(json_path);
    CliConfig c;

    if (auto v = json_find_string(text, "xtc_path")) c.xtc_path = *v;
    const auto max_frames_v = json_find_number_any(text, {"max_frames"});
    const auto frame_begin_v = json_find_number_any(text, {"frame_begin", "begin_frame", "start_frame"});
    const auto frame_end_v = json_find_number_any(text, {"frame_end", "end_frame", "stop_frame"});
    const auto threads_v = json_find_number_any(text, {"threads", "nthreads"});
    const auto grid_cell_v = json_find_number_any(text, {"grid_cell_nm"});
    const auto nsol_v = json_find_number_any(text, {"nsol"});
    const auto nna_v = json_find_number_any(text, {"nna"});
    const auto ncl_v = json_find_number_any(text, {"ncl"});
    const auto xmin_v = json_find_number_any(text, {"xmin"});
    const auto xmax_v = json_find_number_any(text, {"xmax"});
    const auto zmin_v = json_find_number_any(text, {"zmin"});
    const auto zmax_v = json_find_number_any(text, {"zmax"});
    const auto nx_v = json_find_number_any(text, {"nx"});
    const auto nz_v = json_find_number_any(text, {"nz", "density_z_bins"});
    const auto rcw_v = json_find_number_any(text, {"r_cw"});
    const auto raw_v = json_find_number_any(text, {"r_aw"});
    const auto roo_v = json_find_number_any(text, {"r_oo"});
    const auto gating_s_v = json_find_string_any(text, {"gating_sel", "gating_selection"});
    const auto gating_n_v = json_find_number_any(text, {"gating_sel", "gating_selection"});
    const auto out_dir_v = json_find_string_any(text, {"out_dir", "out_prefix"});
    const auto jump_keep_v = json_find_number_any(text, {"jump_keep_frames"});
    const auto bound_layer_v =
        json_find_number_any(text, {"bound_layer_nm", "bound_delta_nm", "adsorption_delta_nm"});

    if (auto v = json_find_string_any(text, {"topology_json", "mini_topology_json", "setup_json"}))
        c.topology_json = *v;
    if (auto v = json_find_bool_or_int_any(
            text, {"use_channel_bounds_from_topology", "use_topology_bounds"}))
        c.use_channel_bounds_from_topology = *v;
    if (auto v = json_find_string_any(text, {"water_names"})) c.water_names = *v;
    if (auto v = json_find_string_any(text, {"na_names"})) c.na_names = *v;
    if (auto v = json_find_string_any(text, {"cl_names"})) c.cl_names = *v;

    apply_topology_counts_from_mini_json(c);

    if (max_frames_v) c.max_frames = parse_int_text(*max_frames_v, "max_frames");
    if (frame_begin_v) c.frame_begin = parse_int_text(*frame_begin_v, "frame_begin");
    if (frame_end_v) c.frame_end = parse_int_text(*frame_end_v, "frame_end");
    if (threads_v) c.nthreads = parse_int_text(*threads_v, "threads");
    if (grid_cell_v) c.grid_cell_nm = parse_double_text(*grid_cell_v, "grid_cell_nm");
    if (nsol_v) c.nsol = parse_int_text(*nsol_v, "nsol");
    if (nna_v) c.nna = parse_int_text(*nna_v, "nna");
    if (ncl_v) c.ncl = parse_int_text(*ncl_v, "ncl");
    if (xmin_v) c.xmin = parse_double_text(*xmin_v, "xmin");
    if (xmax_v) c.xmax = parse_double_text(*xmax_v, "xmax");
    if (zmin_v) c.zmin = parse_double_text(*zmin_v, "zmin");
    if (zmax_v) c.zmax = parse_double_text(*zmax_v, "zmax");
    if (nx_v) c.nx = parse_int_text(*nx_v, "nx");
    if (nz_v) c.nz = parse_int_text(*nz_v, "nz");
    if (rcw_v) c.r_cw = parse_double_text(*rcw_v, "r_cw");
    if (raw_v) c.r_aw = parse_double_text(*raw_v, "r_aw");
    if (roo_v) c.r_oo = parse_double_text(*roo_v, "r_oo");
    if (gating_s_v) c.gating_selection = simio::analysis::parse_gating_selection(*gating_s_v);
    if (gating_n_v) c.gating_selection = simio::analysis::parse_gating_selection(*gating_n_v);
    if (out_dir_v) c.out_dir = *out_dir_v;
    if (jump_keep_v) c.jump_keep_frames = parse_int_text(*jump_keep_v, "jump_keep_frames");
    if (bound_layer_v) c.bound_layer_nm = parse_double_text(*bound_layer_v, "bound_layer_nm");

    validate_cli_config(c);
    return c;
}

CliConfig parse_cli(int argc, char** argv) {
    if (argc < 2) throw std::runtime_error("Missing trajectory path.");

    const std::string arg1 = argv[1];
    if (arg1 == "--config") {
        if (argc < 3) throw std::runtime_error("Missing JSON config path after --config.");
        return parse_json_cli(argv[2]);
    }
    if (argc == 2 && has_suffix(arg1, ".json")) {
        return parse_json_cli(arg1);
    }

    return parse_positional_cli(argc, argv);
}

simio::Topology build_topology(const simio::runtime::RunConfig& cfg) {
    simio::Topology topo;
    int atom_cursor = 0;

    if (cfg.has_mol_blocks && !cfg.mol_blocks.empty()) {
        for (const auto& block : cfg.mol_blocks) {
            const simio::MolType t = block.type;
            const int n = block.nmol;
            const int natoms = block.natoms_per_mol;
            for (int i = 0; i < n; ++i) {
                topo.mols.push_back(simio::MolSpan{atom_cursor, natoms, t});
                atom_cursor += natoms;
            }
        }
    } else {
        for (int i = 0; i < cfg.nsol; ++i) {
            topo.mols.push_back(simio::MolSpan{atom_cursor, 3, simio::MolType::Water});
            atom_cursor += 3;
        }
        for (int i = 0; i < cfg.nna; ++i) {
            topo.mols.push_back(simio::MolSpan{atom_cursor, 1, simio::MolType::Cation});
            atom_cursor += 1;
        }
        for (int i = 0; i < cfg.ncl; ++i) {
            topo.mols.push_back(simio::MolSpan{atom_cursor, 1, simio::MolType::Anion});
            atom_cursor += 1;
        }
    }

    topo.build_type_lists();
    return topo;
}

std::string join_out_path(const std::string& dir, const std::string& filename) {
    const std::filesystem::path p = std::filesystem::path(dir) / filename;
    return p.string();
}

std::filesystem::path copy_report_notebook(const char* executable,
                                           const std::string& output_dir) {
    constexpr const char* notebook_name = "simio_single_run_report.ipynb";
    std::vector<std::filesystem::path> candidates;
    if (const char* configured = std::getenv("SIMIO_REPORT_NOTEBOOK")) {
        candidates.emplace_back(configured);
    }
    candidates.emplace_back(std::filesystem::current_path() / "notebooks" / notebook_name);
    candidates.emplace_back(std::filesystem::absolute(executable).parent_path().parent_path() /
                            "notebooks" / notebook_name);

    const std::filesystem::path destination =
        std::filesystem::path(output_dir) / notebook_name;
    for (const auto& candidate : candidates) {
        std::error_code error;
        if (!std::filesystem::is_regular_file(candidate, error)) continue;
        if (std::filesystem::equivalent(candidate, destination, error) && !error) {
            return destination;
        }
        std::filesystem::copy_file(
            candidate, destination, std::filesystem::copy_options::overwrite_existing);
        return destination;
    }

    throw std::runtime_error(
        "Report notebook template not found. Run from the repository root or set "
        "SIMIO_REPORT_NOTEBOOK.");
}

}  // namespace

int main(int argc, char** argv) {
    try {
        const auto run_start = std::chrono::steady_clock::now();
        simio::runtime::CacheStore cache;
        simio_cache_put_run_meta(cache);

        if (argc < 2) {
            print_usage(argv[0]);
            return 1;
        }

        simio::runtime::RunConfig cfg = simio::runtime::RunConfig::load(argc, argv);
        std::unique_ptr<simio::middle_reservoir::ReactorSetup> middle_setup;
        if (!cfg.gro_path.empty()) {
            middle_setup = std::make_unique<simio::middle_reservoir::ReactorSetup>(
                simio::middle_reservoir::load_reactor_setup(
                    cfg.gro_path, cfg.ion_insertion_report));
            cfg.nsol = middle_setup->nwater;
            cfg.nna = middle_setup->nna;
            cfg.ncl = middle_setup->ncl;
            cfg.xmin = middle_setup->left_gate.x_nm;
            cfg.xmax = middle_setup->right_gate.x_nm;
            cfg.zmin = std::min(middle_setup->left_gate.zmin_nm,
                                middle_setup->right_gate.zmin_nm);
            cfg.zmax = std::max(middle_setup->left_gate.zmax_nm,
                                middle_setup->right_gate.zmax_nm);
            cfg.mol_blocks.clear();
            cfg.has_mol_blocks = false;
        }
        cfg.validate_or_die();

        simio::Topology topo = middle_setup ? middle_setup->topology : build_topology(cfg);
        const int expected_nmols = static_cast<int>(topo.mols.size());
        int expected_natoms = 0;
        if (!topo.mols.empty()) {
            const simio::MolSpan& last = topo.mols.back();
            expected_natoms = last.first + last.natoms;
        }
        if (middle_setup && middle_setup->natoms != expected_natoms) {
            throw std::runtime_error("Middle-reservoir topology atom count is inconsistent");
        }

        std::unique_ptr<simio::middle_reservoir::MiddleReservoirMonitor> middle_monitor;
        if (middle_setup) {
            middle_monitor =
                std::make_unique<simio::middle_reservoir::MiddleReservoirMonitor>(*middle_setup);
        }

        XtcTraj traj{};
        int rc = xtc_open(&traj, cfg.xtc_path.c_str(), /*cap=*/1);
        if (rc != exdrOK) {
            std::cerr << "Failed to open XTC: rc=" << rc << "\n";
            return 1;
        }
        if (traj.natoms != expected_natoms) {
            std::cerr << "Natoms mismatch: file=" << traj.natoms << " expected=" << expected_natoms << "\n";
            xtc_close(&traj);
            return 1;
        }

        simio::Frame fr;
        fr.atoms.x.resize(static_cast<size_t>(expected_natoms));
        fr.atoms.y.resize(static_cast<size_t>(expected_natoms));
        fr.atoms.z.resize(static_cast<size_t>(expected_natoms));

        std::vector<simio::MolState> ms(static_cast<size_t>(expected_nmols));
        auto pipe = simio::make_default_pipeline(cfg.nthreads, cfg.grid_cell_nm);

        simio::analysis::DensityXConfig density_cfg;
        density_cfg.zmin = cfg.zmin;
        density_cfg.zmax = cfg.zmax;
        density_cfg.nx = cfg.nx;
        simio::analysis::DensityXAnalyzer density(density_cfg, cache);
        simio::analysis::WaterAtomDensityXConfig water_atom_density_cfg;
        water_atom_density_cfg.zmin = cfg.zmin;
        water_atom_density_cfg.zmax = cfg.zmax;
        water_atom_density_cfg.nx = cfg.nx;
        simio::analysis::WaterAtomDensityXAnalyzer water_atom_density(water_atom_density_cfg,
                                                                      cache);
        const int nz_eff = (cfg.nz > 0) ? cfg.nz : cfg.nx;
        simio::analysis::DensityZInXChannelConfig density_z_cfg;
        density_z_cfg.xmin = cfg.xmin;
        density_z_cfg.xmax = cfg.xmax;
        density_z_cfg.nz = nz_eff;
        simio::analysis::DensityZInXChannelAnalyzer density_z(density_z_cfg, cache);

        simio::analysis::DipoleZInXChannelConfig dipole_z_cfg;
        dipole_z_cfg.xmin = cfg.xmin;
        dipole_z_cfg.xmax = cfg.xmax;
        dipole_z_cfg.nz = nz_eff;
        simio::analysis::DipoleZInXChannelAnalyzer dipole_z(dipole_z_cfg, cache);

        simio::analysis::DipoleXConfig dipole_cfg;
        // Force dipole ux/uz_fold profile on full x-length [0, Lx).
        // In DipoleXAnalyzer, xmin>=xmax enables whole-box x mode.
        dipole_cfg.xmin = 0.0;
        dipole_cfg.xmax = 0.0;
        dipole_cfg.zmin = cfg.zmin;
        dipole_cfg.zmax = cfg.zmax;
        dipole_cfg.nx = cfg.nx;
        simio::analysis::DipoleXAnalyzer dipole(dipole_cfg, cache);

        simio::analysis::CoordXConfig coord_cfg;
        // Force coordination/HB profiles on full x-length [0, Lx).
        coord_cfg.xmin = 0.0;
        coord_cfg.xmax = 0.0;
        coord_cfg.zmin = cfg.zmin;
        coord_cfg.zmax = cfg.zmax;
        coord_cfg.nx = cfg.nx;
        coord_cfg.nthreads = cfg.nthreads;
        coord_cfg.r_cw = cfg.r_cw;
        coord_cfg.r_aw = cfg.r_aw;
        coord_cfg.r_oo = cfg.r_oo;
        coord_cfg.r_nacl = cfg.r_nacl;
        simio::analysis::CoordXAnalyzer coord(coord_cfg, cache);

        simio::analysis::ChannelCountXZConfig channel_count_cfg;
        channel_count_cfg.xmin = cfg.xmin;
        channel_count_cfg.xmax = cfg.xmax;
        channel_count_cfg.zmin = cfg.zmin;
        channel_count_cfg.zmax = cfg.zmax;
        simio::analysis::ChannelCountXZAnalyzer channel_count(channel_count_cfg);

        simio::analysis::GatingFluxConfig gating_cfg;
        // Force gating channel-x selection on full x-length [0, Lx).
        gating_cfg.xmin = 0.0;
        gating_cfg.xmax = 0.0;
        gating_cfg.zmin = cfg.zmin;
        gating_cfg.zmax = cfg.zmax;
        gating_cfg.selection = simio::analysis::parse_gating_selection(cfg.gating_selection);
        simio::analysis::GatingFluxAnalyzer gating(gating_cfg);

        simio::analysis::JumpMsdConfig jump_cfg;
        jump_cfg.zmin = cfg.zmin;
        jump_cfg.zmax = cfg.zmax;
        jump_cfg.x_channel_min = cfg.xmin;
        jump_cfg.x_channel_max = cfg.xmax;
        jump_cfg.bound_layer_nm = cfg.bound_layer_nm;
        jump_cfg.keep_frames = cfg.jump_keep_frames;
        simio::analysis::JumpMsdAnalyzer jump(jump_cfg);

        std::cout << "[all-props-config] file=" << cfg.xtc_path << " frames=" << cfg.max_frames
                  << " frame_begin=" << cfg.frame_begin << " frame_end=" << cfg.frame_end
                  << " threads=" << cfg.nthreads << " nx=" << cfg.nx << " nz=" << nz_eff
                  << " nsol=" << cfg.nsol << " nna=" << cfg.nna << " ncl=" << cfg.ncl
                  << " nmols_total=" << expected_nmols << " natoms_total=" << expected_natoms
                  << " x_mode=full_box([0,Lx) for density/water-atom-density/dipole/coord/gating]"
                  << " x_channel_for_msd=[" << cfg.xmin << "," << cfg.xmax << "]"
                  << " z=[" << cfg.zmin << "," << cfg.zmax << "] r_cw=" << cfg.r_cw
                  << " r_aw=" << cfg.r_aw << " r_oo=" << cfg.r_oo
                  << " r_nacl=" << cfg.r_nacl
                  << " bound_layer_nm=" << cfg.bound_layer_nm
                  << " jump_keep_frames=" << cfg.jump_keep_frames
                  << " out_dir=" << cfg.out_dir
                  << "\n";

        std::filesystem::create_directories(cfg.out_dir);
        const std::string resolved_config_path =
            join_out_path(cfg.out_dir, "simio_run_config.json");
        cfg.write_json(resolved_config_path);
        if (middle_setup) {
            simio::middle_reservoir::write_setup_json(
                *middle_setup, cfg.gro_path, cfg.ion_insertion_report,
                join_out_path(cfg.out_dir, "middle_reservoir_setup.json"));
        }

        int frames_done = 0;
        int frame_idx_global = 0;
        double x_box_length_nm = 0.0;
        while ((rc = xtc_read_next(&traj)) == exdrOK) {
            const XtcFrame* xr = xtc_tail(&traj);
            if (!xr) {
                xtc_close(&traj);
                throw std::runtime_error("Null frame from reader.");
            }

            const int cur_frame_idx = frame_idx_global;
            frame_idx_global += 1;

            if (cur_frame_idx < cfg.frame_begin) continue;
            if (cfg.frame_end >= 0 && cur_frame_idx >= cfg.frame_end) break;
            if (cfg.max_frames >= 0 && frames_done >= cfg.max_frames) break;

            fr.step = xr->step;
            fr.time_ps = xr->time;
            fr.pbc = simio::Pbc3D(xr->box[0][0], xr->box[1][1], xr->box[2][2]);
            if (fr.pbc.L[0] <= 0.0 || fr.pbc.L[1] <= 0.0 || fr.pbc.L[2] <= 0.0) {
                xtc_close(&traj);
                throw std::runtime_error("Invalid box lengths.");
            }
            if (frames_done == 0) x_box_length_nm = fr.pbc.L[0];

            for (int ai = 0; ai < expected_natoms; ++ai) {
                fr.atoms.x[static_cast<size_t>(ai)] = xr->x[ai][0];
                fr.atoms.y[static_cast<size_t>(ai)] = xr->x[ai][1];
                fr.atoms.z[static_cast<size_t>(ai)] = xr->x[ai][2];
            }

            // One shared intrinsic pass; all analyzers consume cached molecule data.
            pipe.process_frame(topo, fr, ms);

            density.process_frame(topo, fr, ms);
            water_atom_density.process_frame(topo, fr, ms);
            density_z.process_frame(topo, fr, ms);
            dipole_z.process_frame(topo, fr, ms);
            dipole.process_frame(topo, fr, ms);
            coord.process_frame(topo, fr, ms);
            channel_count.process_frame(topo, fr, ms, cur_frame_idx);
            gating.process_frame(topo, fr, ms, cur_frame_idx);
            if (middle_monitor) middle_monitor->process_frame(fr, cur_frame_idx);
            jump.process_frame(topo, fr, ms, cur_frame_idx);

            ++frames_done;
        }

        xtc_close(&traj);
        if (rc != exdrOK && rc != exdrENDOFFILE) {
            throw std::runtime_error("Reader error rc=" + std::to_string(rc));
        }
        if (frames_done == 0) {
            throw std::runtime_error("No frames were processed.");
        }

        const std::string density_csv = join_out_path(cfg.out_dir, "density_x.csv");
        const std::string water_atom_density_csv =
            join_out_path(cfg.out_dir, "water_atom_density_x.csv");
        const std::string axial_profile_csv = join_out_path(cfg.out_dir, "axial_profile_x.csv");
        const std::string density_z_csv = join_out_path(cfg.out_dir, "density_z.csv");
        const std::string dipole_csv = join_out_path(cfg.out_dir, "dipole_x.csv");
        const std::string dipole_z_csv = join_out_path(cfg.out_dir, "dipole_z.csv");
        const std::string coord_csv = join_out_path(cfg.out_dir, "coord_x.csv");
        const std::string channel_count_csv = join_out_path(cfg.out_dir, "channel_count_xz.csv");
        const std::string middle_reservoir_csv = join_out_path(cfg.out_dir, "middle_reservoir.csv");
        const std::string gating_csv = join_out_path(cfg.out_dir, "gating_flux.csv");
        const std::string jump_csv = join_out_path(cfg.out_dir, "jump_msd.csv");
        const std::string jump_channel_x_csv = join_out_path(cfg.out_dir, "msd_x_channel.csv");
        const std::string jump_channel_z_csv = join_out_path(cfg.out_dir, "msd_z_channel.csv");
        const std::string state_channel_csv = join_out_path(cfg.out_dir, "state_z_channel.csv");
        const std::string drift_channel_csv = join_out_path(cfg.out_dir, "drift_channel.csv");
        const std::string vacf_y_csv = join_out_path(cfg.out_dir, "vacf_y.csv");
        const std::string vacf_x_channel_csv = join_out_path(cfg.out_dir, "vacf_x_channel.csv");
        const std::string vacf_z_channel_raw_csv =
            join_out_path(cfg.out_dir, "vacf_z_channel_raw.csv");

        density.write_csv(density_csv);
        water_atom_density.write_csv(water_atom_density_csv);
        simio::analysis::AxialProfileXExportConfig axial_profile_cfg;
        axial_profile_cfg.xmin = cfg.xmin;
        axial_profile_cfg.xmax = cfg.xmax;
        axial_profile_cfg.box_length_x_nm = x_box_length_nm;
        simio::analysis::write_axial_profile_x_csv(axial_profile_csv,
                                                   axial_profile_cfg,
                                                   density,
                                                   water_atom_density,
                                                   dipole,
                                                   coord);
        density_z.write_csv(density_z_csv);
        dipole_z.write_csv(dipole_z_csv);
        dipole.write_csv(dipole_csv);
        coord.write_csv(coord_csv);
        channel_count.write_csv(channel_count_csv);
        if (middle_monitor) middle_monitor->write_csv(middle_reservoir_csv);
        gating.write_csv(gating_csv);
        jump.write_csv(jump_csv);
        jump.write_channel_msd_x_csv(jump_channel_x_csv);
        jump.write_channel_msd_z_csv(jump_channel_z_csv);
        jump.write_state_channel_csv(state_channel_csv);
        jump.write_drift_channel_csv(drift_channel_csv);
        std::array<double, 3> dy_vacf_plateau_nm2_per_ps{0.0, 0.0, 0.0};
        jump.write_vacf_y_csv(vacf_y_csv, &dy_vacf_plateau_nm2_per_ps);
        std::array<double, 3> ix_vacf_channel_plateau_nm2_per_ps{0.0, 0.0, 0.0};
        jump.write_vacf_x_channel_csv(vacf_x_channel_csv, &ix_vacf_channel_plateau_nm2_per_ps);
        std::array<double, 3> iz_vacf_channel_raw_plateau_nm2_per_ps{0.0, 0.0, 0.0};
        jump.write_vacf_z_channel_raw_csv(vacf_z_channel_raw_csv,
                                          &iz_vacf_channel_raw_plateau_nm2_per_ps);
        const std::filesystem::path report_notebook =
            copy_report_notebook(argv[0], cfg.out_dir);

        std::cout << "Processed " << frames_done << " frame(s).\n";
        std::cout << "  wrote: " << resolved_config_path << "\n";
        std::cout << "  wrote: " << density_csv << "\n";
        std::cout << "  wrote: " << water_atom_density_csv << "\n";
        std::cout << "  wrote: " << axial_profile_csv << "\n";
        std::cout << "  wrote: " << density_z_csv << "\n";
        std::cout << "  wrote: " << dipole_csv << "\n";
        std::cout << "  wrote: " << dipole_z_csv << "\n";
        std::cout << "  wrote: " << coord_csv << "\n";
        std::cout << "  wrote: " << channel_count_csv << "\n";
        if (middle_monitor) {
            std::cout << "  wrote: " << middle_reservoir_csv << "\n";
            std::cout << "  wrote: " << join_out_path(cfg.out_dir, "middle_reservoir_setup.json") << "\n";
        }
        std::cout << "  wrote: " << gating_csv << "\n";
        std::cout << "  wrote: " << jump_csv << "\n";
        std::cout << "  wrote: " << jump_channel_x_csv << "\n";
        std::cout << "  wrote: " << jump_channel_z_csv << "\n";
        std::cout << "  wrote: " << state_channel_csv << "\n";
        std::cout << "  wrote: " << drift_channel_csv << "\n";
        std::cout << "  wrote: " << vacf_y_csv << "\n";
        std::cout << "  wrote: " << vacf_x_channel_csv << "\n";
        std::cout << "  wrote: " << vacf_z_channel_raw_csv << "\n";
        std::cout << "  wrote: " << report_notebook.string() << "\n";
        std::cout << "[vacf_y plateau D_y_from_vacf last10 (nm^2/ps)] water="
                  << dy_vacf_plateau_nm2_per_ps[0] << " na=" << dy_vacf_plateau_nm2_per_ps[1]
                  << " cl=" << dy_vacf_plateau_nm2_per_ps[2] << "\n";
        std::cout << "[vacf_x_channel plateau integral last10 (nm^2/ps)] water="
                  << ix_vacf_channel_plateau_nm2_per_ps[0]
                  << " na=" << ix_vacf_channel_plateau_nm2_per_ps[1]
                  << " cl=" << ix_vacf_channel_plateau_nm2_per_ps[2] << "\n";
        std::cout << "[vacf_z_channel_raw plateau integral last10 (nm^2/ps)] water="
                  << iz_vacf_channel_raw_plateau_nm2_per_ps[0]
                  << " na=" << iz_vacf_channel_raw_plateau_nm2_per_ps[1]
                  << " cl=" << iz_vacf_channel_raw_plateau_nm2_per_ps[2] << "\n";
        const auto run_end = std::chrono::steady_clock::now();
        const std::chrono::duration<double> elapsed = run_end - run_start;
        std::cout << "[all-props-runtime] threads=" << cfg.nthreads
                  << " frames=" << frames_done
                  << " elapsed_s=" << elapsed.count()
                  << " seconds_per_frame=" << (elapsed.count() / static_cast<double>(frames_done))
                  << "\n";
        simio_cache_maybe_print_stats(cache);
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }
}
